import * as stylex from '@stylexjs/stylex';

export const aboutStyles = stylex.create({
  about: {
    height: '100%',
    minHeight: 0,
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(230px, 0.88fr) minmax(360px, 1.12fr)',
      '@media (max-width: 1100px)': '1fr',
    },
    alignItems: 'center',
    overflowY: 'auto',
    scrollbarWidth: 'thin',
    gap: {
      default: 'clamp(1.5rem, 3vw, 3rem)',
      '@media (max-width: 1100px)': '1rem',
    },
    padding: {
      default: 'clamp(0.85rem, 2vw, 1.5rem)',
      '@media (max-width: 1100px)': '0.75rem',
    },
    color: '#d7d0c7',
    backgroundColor: 'rgba(10, 8, 13, 0.97)',
    fontSize: 'clamp(0.72rem, 1.05vw, 0.92rem)',
    lineHeight: 1.45,
  },
  markWrap: {
    minWidth: 0,
    display: 'grid',
    alignContent: 'center',
    gap: '0.9rem',
    placeItems: 'center',
    padding: {
      default: 'clamp(0.75rem, 1.5vw, 1.25rem)',
      '@media (max-width: 1100px)': '0.35rem',
    },
  },
  mark: {
    width: {
      default: 'min(86%, 280px)',
      '@media (max-height: 800px)': 'min(72%, 220px)',
      '@media (max-width: 1100px)': 'min(34vw, 120px)',
    },
    height: 'auto',
    display: 'block',
    color: '#7dc79f',
    fill: 'currentColor',
  },
  markCaption: {
    width: 'min(86%, 280px)',
    margin: 0,
    paddingTop: '0.65rem',
    display: 'flex',
    justifyContent: 'space-between',
    gap: '0.75rem',
    color: '#957a99',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#6c586d',
    fontSize: '0.64rem',
    letterSpacing: '0.09em',
  },
  readout: {
    minWidth: 0,
    display: 'grid',
    gap: 'clamp(0.9rem, 1.6vw, 1.35rem)',
  },
  host: {
    minWidth: 0,
    display: 'grid',
    gap: '0.4rem',
  },
  hostName: {
    margin: 0,
    color: '#d7d0c7',
    fontSize: '1rem',
    fontWeight: 600,
    letterSpacing: '0.025em',
  },
  hostRule: {
    width: '100%',
    height: '1px',
    display: 'block',
    backgroundColor: '#6c586d',
  },
  hostAccent: {
    color: '#7dc79f',
  },
  group: {
    position: 'relative',
    minWidth: 0,
    padding: '1.05rem 1.1rem 0.9rem',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#6c586d',
    backgroundColor: 'rgba(255, 255, 255, 0.012)',
  },
  hardware: {
    borderColor: 'rgba(125, 199, 159, 0.58)',
  },
  software: {
    borderColor: 'rgba(120, 146, 200, 0.58)',
  },
  session: {
    borderColor: 'rgba(182, 122, 199, 0.58)',
  },
  legend: {
    position: 'absolute',
    top: '-0.65em',
    left: '50%',
    margin: 0,
    paddingInline: '0.45rem',
    color: 'inherit',
    backgroundColor: '#0a080d',
    fontSize: '0.76rem',
    fontWeight: 500,
    transform: 'translateX(-50%)',
    whiteSpace: 'nowrap',
  },
  list: {
    minWidth: 0,
    margin: 0,
    display: 'grid',
    gap: '0.34rem',
  },
  row: {
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: 'minmax(7rem, auto) minmax(0, 1fr)',
    gap: '0.8rem',
  },
  key: {
    color: '#7dc79f',
    fontWeight: 600,
  },
  softwareKey: {
    color: '#7892c8',
    fontWeight: 700,
  },
  sessionKey: {
    color: '#b67ac7',
    fontWeight: 700,
  },
  value: {
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
    color: '#d7d0c7',
    fontVariantNumeric: 'tabular-nums',
  },
  swatches: {
    minWidth: 0,
    minHeight: '1em',
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.12rem',
  },
  swatch: {
    width: '0.78em',
    height: '0.78em',
    display: 'block',
    flex: '0 0 auto',
    borderRadius: '50%',
  },
});
