import * as stylex from '@stylexjs/stylex';

const c = { bg: '#0f0b12', text: '#d8d0c8', dim: '#8c7f8e', purple: '#a76caf', pink: '#d75b91', green: '#76c7a0', cyan: '#58b8bb', red: '#ce5068' };

export const btopStyles = stylex.create({
  home: { height: '100%', minHeight: 0, padding: '0.55rem', display: 'grid', gridTemplateRows: 'auto minmax(0, 1fr)', gap: '0.35rem', overflow: 'hidden', color: c.text, backgroundColor: c.bg, fontSize: 'clamp(0.55rem, 0.8vw, 0.78rem)', lineHeight: 1.25 },
  topbar: { minWidth: 0, minHeight: '26px', display: 'grid', gridTemplateColumns: 'auto auto auto 1fr auto', alignItems: 'center', gap: '0.65rem', paddingInline: '0.45rem', color: c.text, borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: c.purple },
  pink: { color: c.pink },
  clock: { justifySelf: 'center', fontVariantNumeric: 'tabular-nums' },
  pauseButton: { minWidth: '44px', minHeight: '28px', paddingInline: '0.45rem', color: { default: c.text, ':hover': c.bg, ':active': c.bg }, backgroundColor: { default: 'transparent', ':hover': c.purple, ':active': c.purple }, borderWidth: '1px', borderStyle: 'solid', borderColor: c.purple, font: 'inherit', cursor: 'pointer' },
  grid: { minWidth: 0, minHeight: 0, display: 'grid', gridTemplateColumns: { default: 'minmax(110px, 0.6fr) minmax(120px, 0.62fr) minmax(260px, 1.38fr)', '@media (max-width: 720px)': '1fr 1fr' }, gridTemplateRows: { default: 'minmax(145px, 1.2fr) minmax(92px, 0.8fr) minmax(92px, 0.8fr)', '@media (max-width: 720px)': 'minmax(180px, auto) auto auto auto' }, gridTemplateAreas: { default: '"cpu cpu cpu" "mem disk proc" "net disk proc"', '@media (max-width: 720px)': '"cpu cpu" "mem disk" "net disk" "proc proc"' }, gap: '0.35rem' },
  panel: { position: 'relative', minWidth: 0, minHeight: 0, padding: '0.5rem 0.55rem', borderWidth: '1px', borderStyle: 'solid', borderRadius: '2px', overflow: 'hidden', backgroundColor: c.bg },
  cpuPanel: { gridArea: 'cpu', borderColor: c.purple, display: 'grid', gridTemplateRows: 'auto minmax(0, 1fr) auto' },
  memoryPanel: { gridArea: 'mem', borderColor: c.green },
  diskPanel: { gridArea: 'disk', borderColor: c.green },
  networkPanel: { gridArea: 'net', borderColor: c.red },
  processPanel: { gridArea: 'proc', borderColor: c.pink, display: 'grid', gridTemplateRows: 'auto auto minmax(0, 1fr) auto' },
  panelHeading: { minWidth: 0, minHeight: '18px', display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: '0.55rem', marginTop: '-0.25rem', color: c.dim },
  panelTitle: { margin: 0, paddingInline: '0.15rem', color: c.purple, backgroundColor: c.bg, fontSize: 'inherit', fontWeight: 700, letterSpacing: '0.025em' },
  cpuBody: { minHeight: 0, display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(230px, 1fr)', gap: '0.65rem' },
  chart: { minHeight: '60px', display: 'flex', alignItems: 'flex-end', gap: '2px', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: c.purple },
  chartBar: { minWidth: '2px', flexGrow: 1, backgroundColor: c.cyan, opacity: 0.7 },
  chartBarCurrent: { backgroundColor: c.green, opacity: 1 },
  coreGrid: { minWidth: 0, display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', alignContent: 'start', gap: '0.04rem 0.7rem', overflow: 'hidden', fontVariantNumeric: 'tabular-nums' },
  coreRow: { minWidth: 0, display: 'grid', gridTemplateColumns: '2.2em minmax(0, 1fr) 2.8em 2.7em', gap: '0.22rem' },
  coreMeter: { minWidth: 0, overflow: 'hidden', color: c.cyan, whiteSpace: 'nowrap' },
  uptime: { margin: '0.2rem 0 0', display: 'flex', justifyContent: 'space-between', color: c.dim, fontVariantNumeric: 'tabular-nums' },
  emptyState: { margin: 0, alignSelf: 'center', color: c.dim },
  stackList: { margin: '0.35rem 0 0', display: 'grid', gap: '0.2rem', fontVariantNumeric: 'tabular-nums' },
  blockGraph: { marginTop: '0.55rem', color: c.cyan, letterSpacing: '0.08em', overflow: 'hidden' },
  memoryMeter: { height: '44px', marginTop: '0.45rem', display: 'flex', alignItems: 'flex-end', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: c.green },
  diskList: { margin: '0.3rem 0 0', display: 'grid', gap: '0.6rem', color: c.text },
  netGraph: { minHeight: '45px', display: 'flex', alignItems: 'end', marginBlock: '0.35rem', color: c.cyan, letterSpacing: '0.08em', overflow: 'hidden' },
  networkState: { color: c.green },
  networkOffline: { color: c.red },
  processHeader: { display: 'grid', gridTemplateColumns: '3.2rem minmax(0, 1fr) 3.5rem 3rem', gap: '0.35rem', paddingBlock: '0.2rem', color: c.text, borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: c.purple },
  processList: { minHeight: 0, overflowY: 'auto', scrollbarWidth: 'thin' },
  processRow: { width: '100%', minHeight: { default: '30px', '@media (max-width: 720px)': '44px' }, display: 'grid', gridTemplateColumns: '3.2rem minmax(0, 1fr) 3.5rem 3rem', alignItems: 'center', gap: '0.35rem', padding: '0 0.2rem', color: { default: c.text, ':hover': c.bg, ':active': c.bg }, backgroundColor: { default: 'transparent', ':hover': c.green, ':active': c.green }, borderWidth: 0, font: 'inherit', textAlign: 'left', cursor: 'pointer' },
  processSelected: { color: c.bg, backgroundColor: c.green },
  processStaticRow: { minHeight: '25px', display: 'grid', gridTemplateColumns: '3.2rem minmax(0, 1fr) 3.5rem 3rem', alignItems: 'center', gap: '0.35rem', paddingInline: '0.2rem', color: c.dim, fontVariantNumeric: 'tabular-nums' },
  processFooter: { display: 'flex', justifyContent: 'space-between', gap: '0.5rem', paddingTop: '0.3rem', color: c.dim, borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: c.purple },
  focusRing: { outline: { default: 'none', ':focus-visible': `2px solid ${c.green}` }, outlineOffset: { default: 0, ':focus-visible': '2px' } },
});
