import * as stylex from '@stylexjs/stylex';
import { tokens } from './landing.stylex';

export const graphStyles = stylex.create({
  focusRing: {
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${tokens.green}`,
    },
    outlineOffset: {
      default: 0,
      ':focus-visible': '3px',
    },
  },
  graph: {
    minWidth: 0,
    display: 'grid',
    gap: '0.65rem',
  },
  header: {
    minHeight: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingBottom: '0.65rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(242, 236, 227, 0.24)',
  },
  heading: {
    minWidth: 0,
    display: 'grid',
    gap: '0.14rem',
  },
  eyebrow: {
    color: tokens.green,
    fontSize: '0.62rem',
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  title: {
    margin: 0,
    overflow: 'hidden',
    color: '#f2ece3',
    fontSize: '0.82rem',
    fontWeight: 500,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
  },
  action: {
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingInline: '0.7rem',
    color: {
      default: '#f2ece3',
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(242, 236, 227, 0.38)',
    borderRadius: 0,
    font: 'inherit',
    fontSize: '0.68rem',
    textDecorationLine: 'none',
    cursor: 'pointer',
  },
  trail: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    overflowX: 'auto',
    scrollbarWidth: 'thin',
  },
  trailLabel: {
    flexShrink: 0,
    color: '#948d88',
    fontSize: '0.62rem',
  },
  trailButton: {
    minHeight: '44px',
    maxWidth: '16rem',
    flexShrink: 0,
    paddingInline: '0.65rem',
    overflow: 'hidden',
    color: {
      default: '#b7afb0',
      ':hover': '#ff75ad',
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': '#282229',
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(242, 236, 227, 0.22)',
    borderRadius: 0,
    font: 'inherit',
    fontSize: '0.64rem',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
  },
  stage: {
    position: 'relative',
    minWidth: 0,
    height: {
      default: '500px',
      '@media (max-width: 620px)': '660px',
    },
    overflow: 'hidden',
    backgroundColor: '#0b0a0e',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(242, 236, 227, 0.2)',
  },
  stageCompact: {
    height: '660px',
  },
  canvas: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    width: '100%',
    height: '100%',
    display: 'block',
    opacity: 0,
    pointerEvents: 'none',
    transitionProperty: 'opacity',
    transitionDuration: {
      default: '120ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionTimingFunction: 'linear',
  },
  canvasReady: {
    opacity: 1,
  },
  rootNode: {
    position: 'absolute',
    zIndex: 2,
    left: '50%',
    top: {
      default: '50%',
      '@media (max-width: 620px)': '13%',
    },
    width: {
      default: 'min(220px, 30%)',
      '@media (max-width: 620px)': 'min(240px, calc(100% - 32px))',
    },
    minHeight: '82px',
    display: 'grid',
    alignContent: 'center',
    gap: '0.3rem',
    padding: '0.75rem 0.85rem',
    color: '#f2ece3',
    backgroundColor: '#17131b',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: tokens.green,
    boxShadow: '0 0.8rem 2.2rem rgba(0, 0, 0, 0.44)',
    textAlign: 'center',
    transform: 'translate(-50%, -50%)',
  },
  rootNodeCompact: {
    top: '13%',
    width: 'min(240px, calc(100% - 32px))',
  },
  rootKind: {
    color: tokens.green,
    fontSize: '0.6rem',
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  rootTitle: {
    overflowWrap: 'anywhere',
    fontSize: '0.78rem',
    fontWeight: 600,
    lineHeight: 1.35,
  },
  node: {
    position: 'absolute',
    zIndex: 2,
    width: {
      default: 'min(176px, 23%)',
      '@media (max-width: 620px)': '43%',
    },
    minHeight: {
      default: '72px',
      '@media (max-width: 620px)': '82px',
    },
    display: 'grid',
    alignContent: 'center',
    gap: '0.25rem',
    padding: '0.6rem 0.65rem',
    overflow: 'hidden',
    color: {
      default: '#d4ccca',
      ':hover': '#0a0a0d',
      ':active': '#0a0a0d',
    },
    backgroundColor: {
      default: '#151218',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: 'rgba(242, 236, 227, 0.42)',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderRadius: 0,
    font: 'inherit',
    textAlign: 'left',
    cursor: 'pointer',
    transform: 'translate(-50%, -50%)',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '100ms',
    transitionTimingFunction: 'linear',
  },
  nodeCompact: {
    width: '43%',
    minHeight: '82px',
  },
  nodeActive: {
    color: '#ff75ad',
    backgroundColor: '#282229',
    borderColor: '#ff75ad',
  },
  nodeKind: {
    overflow: 'hidden',
    fontSize: '0.58rem',
    letterSpacing: '0.06em',
    opacity: 0.72,
    textOverflow: 'ellipsis',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  nodeTitle: {
    maxHeight: '2.7em',
    overflow: 'hidden',
    overflowWrap: 'anywhere',
    fontSize: {
      default: '0.7rem',
      '@media (max-width: 620px)': '0.68rem',
    },
    fontWeight: 600,
    lineHeight: 1.35,
  },
  stageState: {
    position: 'absolute',
    zIndex: 3,
    left: '50%',
    bottom: '0.7rem',
    maxWidth: 'calc(100% - 24px)',
    margin: 0,
    padding: '0.35rem 0.5rem',
    color: '#b7afb0',
    backgroundColor: 'rgba(11, 10, 14, 0.88)',
    fontSize: '0.62rem',
    lineHeight: 1.4,
    textAlign: 'center',
    transform: 'translateX(-50%)',
  },
  footer: {
    margin: 0,
    color: '#948d88',
    fontSize: '0.64rem',
    lineHeight: 1.5,
  },
});
