import * as stylex from '@stylexjs/stylex';

export const tokens = stylex.defineVars({
  ink: '#f0eef5',
  muted: '#a5a2ad',
  black: '#0a0a0d',
  panel: '#11121a',
  line: 'rgba(240, 238, 245, 0.2)',
  lineStrong: 'rgba(240, 238, 245, 0.38)',
  surface: 'rgba(13, 13, 18, 0.72)',
  blue: '#7aa2f7',
  green: '#9ece6a',
  turquoise: '#73daca',
});

export const styles = stylex.create({
  page: {
    minHeight: '100vh',
    overflow: 'hidden',
    backgroundColor: tokens.black,
    backgroundImage: 'radial-gradient(circle at 15% 24%, rgba(122, 162, 247, 0.08), transparent 24rem)',
  },
  contentWidth: {
    width: {
      default: 'min(1280px, calc(100% - 48px))',
      '@media (max-width: 720px)': 'min(1280px, calc(100% - 30px))',
    },
    marginInline: 'auto',
  },
  focusRing: {
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${tokens.green}`,
    },
    outlineOffset: {
      default: 0,
      ':focus-visible': '4px',
    },
  },
  skipLink: {
    position: 'fixed',
    zIndex: 100,
    top: '0.75rem',
    left: '0.75rem',
    paddingBlock: '0.7rem',
    paddingInline: '0.9rem',
    color: tokens.black,
    backgroundColor: tokens.green,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.black,
    transform: {
      default: 'translateY(-160%)',
      ':focus': 'translateY(0)',
    },
  },
  announcement: {
    minHeight: '34px',
    display: 'grid',
    placeItems: 'center',
    paddingBlock: '0.45rem',
    paddingInline: '1rem',
    color: tokens.black,
    backgroundColor: tokens.green,
    fontSize: {
      default: '0.68rem',
      '@media (max-width: 420px)': '0.6rem',
    },
    fontWeight: 700,
    letterSpacing: '0.02em',
    textAlign: 'center',
  },
  announcementLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.55rem',
    textDecorationLine: {
      default: 'none',
      ':hover': 'underline',
    },
    textUnderlineOffset: '0.2em',
  },
  liveDot: {
    width: '0.48rem',
    height: '0.48rem',
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: tokens.black,
  },
  heroShell: {
    position: 'relative',
    isolation: 'isolate',
    minHeight: {
      default: 'min(790px, calc(100svh - 110px))',
      '@media (max-width: 980px)': 'auto',
    },
    backgroundImage: {
      default: "linear-gradient(90deg, rgba(8, 8, 12, 0.95) 0%, rgba(8, 8, 12, 0.78) 43%, rgba(8, 8, 12, 0.42) 100%), linear-gradient(180deg, rgba(8, 8, 12, 0.1), rgba(8, 8, 12, 0.82)), url('/images/silk.webp')",
      '@media (max-width: 980px)': "linear-gradient(180deg, rgba(8, 8, 12, 0.84), rgba(8, 8, 12, 0.66) 56%, rgba(8, 8, 12, 0.9)), url('/images/silk.webp')",
    },
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  hero: {
    minHeight: 'inherit',
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(290px, 0.72fr) minmax(0, 1.28fr)',
      '@media (max-width: 980px)': '1fr',
    },
    alignItems: 'center',
    gap: {
      default: 'clamp(2.5rem, 6vw, 6rem)',
      '@media (max-width: 980px)': '3.6rem',
      '@media (max-width: 720px)': '3rem',
    },
    paddingBlock: {
      default: 'clamp(4rem, 8vw, 7rem)',
      '@media (max-width: 720px)': '4rem 4.5rem',
    },
  },
  heroTitle: {
    maxWidth: {
      default: '10ch',
      '@media (max-width: 980px)': '12ch',
    },
    margin: 0,
    color: tokens.ink,
    fontSize: {
      default: 'clamp(3.3rem, 6vw, 6.7rem)',
      '@media (max-width: 720px)': 'clamp(2.85rem, 13vw, 5rem)',
      '@media (max-width: 420px)': 'clamp(2.7rem, 14vw, 3.6rem)',
    },
    fontWeight: 500,
    letterSpacing: {
      default: '-0.075em',
      '@media (max-width: 720px)': '-0.07em',
    },
    lineHeight: 0.95,
  },
  heroTitleLink: {
    color: tokens.blue,
    textDecorationThickness: '0.08em',
    textUnderlineOffset: '0.12em',
  },
  officialLinks: {
    width: {
      default: 'min(1000px, calc(100% - 48px))',
      '@media (max-width: 720px)': 'min(1000px, calc(100% - 30px))',
    },
    marginInline: 'auto',
    paddingBlock: {
      default: 'clamp(4rem, 8vw, 7rem)',
      '@media (max-width: 720px)': '4.5rem',
    },
    display: 'grid',
    gap: '0.8rem',
  },
  linkRow: {
    display: {
      default: 'flex',
      '@media (max-width: 720px)': 'grid',
    },
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: '0.8rem',
  },
  navLink: {
    minWidth: {
      default: '8.5rem',
      '@media (max-width: 720px)': 0,
    },
    minHeight: '46px',
    display: 'inline-grid',
    placeItems: 'center',
    paddingBlock: '0.78rem',
    paddingInline: {
      default: '1.25rem',
      '@media (max-width: 720px)': '0.65rem',
    },
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
    },
    backgroundColor: {
      default: tokens.surface,
      ':hover': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.green,
    },
    fontSize: {
      default: '0.75rem',
      '@media (max-width: 420px)': '0.68rem',
    },
    fontWeight: 600,
    letterSpacing: '0.05em',
    textDecorationLine: 'none',
    transform: {
      default: 'translateY(0)',
      ':hover': 'translateY(-2px)',
    },
    transitionProperty: 'color, background-color, border-color, transform',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
  },
  videoGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 720px)': '1fr',
    },
    gap: '1.35rem',
    paddingBottom: {
      default: 'clamp(5rem, 9vw, 8rem)',
      '@media (max-width: 720px)': '5rem',
    },
  },
  videoFrame: {
    position: 'relative',
    overflow: 'hidden',
    aspectRatio: '16 / 9',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    backgroundColor: tokens.panel,
  },
  videoFill: {
    width: '100%',
    height: '100%',
    borderWidth: 0,
  },
  videoFacade: {
    position: 'relative',
    display: 'block',
    padding: 0,
    color: tokens.ink,
    backgroundColor: tokens.panel,
    cursor: 'pointer',
  },
  videoImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  videoShade: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(180deg, transparent 52%, rgba(0, 0, 0, 0.44))',
    pointerEvents: 'none',
  },
  play: {
    position: 'absolute',
    zIndex: 1,
    top: '50%',
    left: '50%',
    width: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    height: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    display: 'grid',
    placeItems: 'center',
    backgroundColor: tokens.green,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.black,
    transform: 'translate(-50%, -50%)',
  },
  playIcon: {
    width: 0,
    height: 0,
    marginLeft: '4px',
    borderTop: '9px solid transparent',
    borderBottom: '9px solid transparent',
    borderLeft: `14px solid ${tokens.black}`,
  },
  footer: {
    paddingBlock: {
      default: '3.5rem 4rem',
      '@media (max-width: 720px)': '3rem 3.5rem',
    },
    display: 'grid',
    gap: '0.7rem',
    color: tokens.muted,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
    fontSize: '0.7rem',
    lineHeight: 1.65,
    textAlign: 'center',
  },
  footerParagraph: {
    margin: 0,
  },
  footerLink: {
    color: {
      default: tokens.ink,
      ':hover': tokens.green,
    },
    textDecorationColor: tokens.lineStrong,
    textUnderlineOffset: '0.24em',
  },
});
