import * as stylex from '@stylexjs/stylex';
import { tokens } from './landing.stylex';

export const desktopStyles = stylex.create({
  desktop: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
    height: {
      default: 'clamp(820px, 92svh, 980px)',
      '@media (max-width: 720px)': 'min(820px, calc(100svh - 18px))',
    },
    minHeight: {
      default: '820px',
      '@media (max-width: 720px)': '680px',
    },
    isolation: 'isolate',
    color: tokens.ink,
    backgroundColor: '#11121a',
    backgroundImage: "url('/images/silk.webp')",
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  canvas: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    width: '100%',
    height: '100%',
    display: 'block',
    opacity: 0,
    pointerEvents: 'none',
    transitionProperty: 'opacity',
    transitionDuration: {
      default: '180ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionTimingFunction: 'ease-out',
  },
  canvasReady: {
    opacity: 1,
  },
  shade: {
    position: 'absolute',
    zIndex: 1,
    inset: 0,
    pointerEvents: 'none',
    backgroundImage: 'linear-gradient(180deg, rgba(4, 5, 8, 0.18), rgba(4, 5, 8, 0.36))',
  },
  topbar: {
    position: 'absolute',
    zIndex: 80,
    top: 0,
    left: 0,
    right: 0,
    height: '46px',
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr auto 1fr',
      '@media (max-width: 540px)': '1fr auto',
    },
    alignItems: 'center',
    paddingInline: {
      default: '0.75rem',
      '@media (max-width: 540px)': '0.5rem',
    },
    color: tokens.ink,
    backgroundColor: 'rgba(8, 9, 13, 0.9)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.lineStrong,
    fontSize: '0.75rem',
    userSelect: 'none',
  },
  topbarEditing: {
    borderBottomColor: tokens.green,
  },
  shellStart: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: {
      default: '0.75rem',
      '@media (max-width: 540px)': '0.25rem',
    },
  },
  shellMenu: {
    width: '44px',
    height: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: '7px',
    color: tokens.ink,
    backgroundColor: 'transparent',
    borderWidth: 0,
    cursor: 'pointer',
  },
  shellMenuActive: {
    backgroundColor: 'rgba(240, 238, 245, 0.08)',
  },
  shellLogo: {
    width: '28px',
    height: '28px',
    display: 'block',
  },
  workspaces: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.3rem',
  },
  workspace: {
    width: '44px',
    height: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    color: tokens.muted,
    backgroundColor: 'transparent',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    font: 'inherit',
    cursor: 'pointer',
  },
  workspaceActive: {
    color: tokens.black,
    backgroundColor: tokens.green,
    borderColor: tokens.green,
  },
  activeApp: {
    display: {
      default: 'inline',
      '@media (max-width: 540px)': 'none',
    },
    maxWidth: {
      default: '28ch',
      '@media (max-width: 540px)': '14ch',
    },
    overflow: 'hidden',
    color: tokens.muted,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  shellWidgets: {
    minWidth: 0,
    maxWidth: {
      default: '100%',
      '@media (max-width: 540px)': '146px',
    },
    justifySelf: 'end',
    display: 'flex',
    alignItems: 'center',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  shellWidget: {
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    paddingInline: '0.55rem',
    color: {
      default: tokens.muted,
      ':hover': tokens.ink,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': 'rgba(240, 238, 245, 0.08)',
      ':active': tokens.green,
    },
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.line,
    font: 'inherit',
    fontVariantNumeric: 'tabular-nums',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
  },
  shellWidgetActive: {
    color: tokens.black,
    backgroundColor: tokens.green,
  },
  shellWidgetAlert: {
    color: '#f7768e',
  },
  shellWidgetIcon: {
    width: '15px',
    height: '15px',
    flexShrink: 0,
    display: 'block',
  },
  shellWidgetEmpty: {
    paddingInline: '0.55rem',
    color: tokens.muted,
    whiteSpace: 'nowrap',
  },
  shellPopover: {
    position: 'absolute',
    zIndex: 94,
    top: '54px',
    right: '8px',
    width: {
      default: 'min(480px, calc(100% - 16px))',
      '@media (max-width: 720px)': 'calc(100% - 16px)',
    },
    maxHeight: 'calc(100% - 62px)',
    overflowY: 'auto',
    padding: '0.9rem 1rem 1rem',
    color: tokens.ink,
    backgroundColor: 'rgba(15, 13, 21, 0.98)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    borderTopColor: tokens.green,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.58)',
  },
  shellPopoverHeader: {
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingBottom: '0.65rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  shellPopoverHeading: {
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.55rem',
  },
  shellPopoverTitle: {
    margin: 0,
    color: tokens.ink,
    fontSize: '0.88rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
  },
  shellPopoverClose: {
    width: '44px',
    height: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    color: {
      default: tokens.muted,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: 0,
    font: 'inherit',
    fontSize: '1.15rem',
    cursor: 'pointer',
  },
  calendarLead: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    paddingBlock: '0.9rem 0.25rem',
  },
  calendarLeadIcon: {
    width: '42px',
    height: '42px',
    flexShrink: 0,
    color: tokens.green,
  },
  calendarLeadDate: {
    fontSize: {
      default: '2.35rem',
      '@media (max-width: 420px)': '1.8rem',
    },
    fontWeight: 600,
    lineHeight: 1,
  },
  calendarEvent: {
    margin: '0 0 0.8rem 3.25rem',
    color: tokens.muted,
    fontSize: '0.7rem',
  },
  calendarWeekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    paddingBlock: '0.4rem',
    color: tokens.muted,
    fontSize: '0.62rem',
    letterSpacing: '0.08em',
    textAlign: 'center',
  },
  calendarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
    gap: '2px',
  },
  calendarDay: {
    minHeight: '36px',
    display: 'grid',
    placeItems: 'center',
    color: tokens.ink,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    fontSize: '0.72rem',
    fontVariantNumeric: 'tabular-nums',
  },
  calendarDayOutside: {
    color: '#817c86',
  },
  calendarDayToday: {
    color: tokens.ink,
    borderColor: tokens.lineStrong,
    backgroundColor: 'rgba(240, 238, 245, 0.08)',
  },
  calendarMonthNav: {
    minHeight: '44px',
    display: 'grid',
    gridTemplateColumns: '44px minmax(0, 1fr) 44px',
    alignItems: 'center',
    marginTop: '0.45rem',
  },
  calendarNavButton: {
    width: '44px',
    height: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: 0,
    font: 'inherit',
    fontSize: '1.25rem',
    cursor: 'pointer',
  },
  calendarMonthLabel: {
    minWidth: 0,
    overflow: 'hidden',
    color: tokens.muted,
    fontSize: '0.7rem',
    letterSpacing: '0.08em',
    textAlign: 'center',
    textOverflow: 'ellipsis',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  shellMetric: {
    margin: '1rem 0 0.75rem',
    color: tokens.green,
    fontSize: {
      default: '2.1rem',
      '@media (max-width: 420px)': '1.7rem',
    },
    fontWeight: 600,
    fontVariantNumeric: 'tabular-nums',
    lineHeight: 1,
  },
  shellMetricAlert: {
    color: '#f7768e',
  },
  shellDetails: {
    margin: 0,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
  },
  shellDetailRow: {
    minHeight: '44px',
    display: 'grid',
    gridTemplateColumns: 'minmax(8rem, 0.8fr) minmax(0, 1.2fr)',
    alignItems: 'center',
    gap: '0.75rem',
    paddingBlock: '0.35rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
    color: tokens.muted,
    fontSize: '0.72rem',
  },
  shellDetailTerm: {
    minWidth: 0,
  },
  shellDetailValue: {
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
    color: tokens.ink,
    textAlign: 'right',
  },
  shellControlLabel: {
    margin: '0.9rem 0 0.45rem',
    color: tokens.muted,
    fontSize: '0.66rem',
    fontWeight: 500,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  textSizeControls: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '0.35rem',
  },
  textSizeButton: {
    minWidth: 0,
    minHeight: '44px',
    paddingInline: '0.35rem',
    color: {
      default: tokens.muted,
      ':hover': tokens.ink,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': 'rgba(240, 238, 245, 0.08)',
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    font: 'inherit',
    fontSize: '0.7rem',
    cursor: 'pointer',
  },
  textSizeButtonActive: {
    color: tokens.black,
    backgroundColor: tokens.green,
    borderColor: tokens.green,
  },
  shellPopoverNote: {
    margin: '0.8rem 0 0',
    color: tokens.muted,
    fontSize: '0.68rem',
    lineHeight: 1.5,
  },
  widgetEditor: {
    position: 'absolute',
    zIndex: 95,
    top: '54px',
    left: '50%',
    width: {
      default: 'min(430px, calc(100% - 32px))',
      '@media (max-width: 720px)': 'calc(100% - 16px)',
    },
    maxHeight: 'calc(100% - 62px)',
    overflowY: 'auto',
    padding: '0.75rem',
    color: tokens.ink,
    backgroundColor: '#11121a',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.green,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.52)',
    transform: 'translateX(-50%)',
  },
  widgetEditorHeader: {
    display: 'flex',
    alignItems: 'start',
    justifyContent: 'space-between',
    gap: '0.75rem',
    marginBottom: '0.75rem',
    paddingBottom: '0.7rem',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  widgetEditorTitle: {
    margin: 0,
    color: tokens.ink,
    fontSize: '0.82rem',
    fontWeight: 600,
  },
  widgetEditorHint: {
    margin: '0.2rem 0 0',
    color: tokens.muted,
    fontSize: '0.68rem',
    lineHeight: 1.45,
  },
  widgetEditorClose: {
    minWidth: '68px',
    minHeight: '44px',
    paddingInline: '0.7rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    font: 'inherit',
    fontSize: '0.72rem',
    cursor: 'pointer',
  },
  widgetEditorList: {
    display: 'grid',
    gap: '0.4rem',
  },
  widgetOption: {
    minWidth: 0,
    minHeight: '52px',
    display: 'grid',
    gridTemplateColumns: '22px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: '0.75rem',
    paddingInline: '0.85rem',
    color: {
      default: tokens.muted,
      ':hover': tokens.ink,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'rgba(240, 238, 245, 0.04)',
      ':hover': 'rgba(240, 238, 245, 0.08)',
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.lineStrong,
      ':active': tokens.green,
    },
    font: 'inherit',
    fontSize: '0.75rem',
    textAlign: 'left',
    cursor: 'pointer',
  },
  widgetOptionActive: {
    color: tokens.ink,
    borderColor: tokens.green,
  },
  widgetOptionLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  widgetOptionState: {
    color: 'inherit',
    fontSize: '0.68rem',
    whiteSpace: 'nowrap',
  },
  windowsLayer: {
    position: 'absolute',
    zIndex: 10,
    inset: {
      default: '46px 0 0',
      '@media (max-width: 720px)': '46px 0 0',
    },
  },
  homeStackLayer: {
    overflowX: 'hidden',
    overflowY: 'auto',
    display: 'grid',
    alignContent: 'start',
    gap: '4px',
    padding: '4px 4px 0.75rem',
    scrollPaddingBlock: '4px 0.75rem',
  },
  emptyWorkspace: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    padding: '2rem',
    color: tokens.ink,
    fontSize: {
      default: '0.8rem',
      '@media (max-width: 720px)': '0.75rem',
    },
    textAlign: 'center',
  },
  window: {
    position: 'absolute',
    minWidth: '280px',
    minHeight: '210px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    color: tokens.ink,
    backgroundColor: 'rgba(12, 13, 19, 0.96)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.42)',
  },
  windowFocused: {
    borderColor: tokens.green,
    boxShadow: '0 1.75rem 4.5rem rgba(0, 0, 0, 0.5)',
  },
  windowMaximized: {
    inset: '8px',
    width: 'auto',
    height: 'auto',
  },
  windowMobile: {
    inset: '8px',
    width: 'auto',
    height: 'auto',
    minWidth: 0,
    minHeight: 0,
  },
  homeStackWindow: {
    position: 'relative',
    inset: 'auto',
    width: '100%',
    height: 'auto',
    minWidth: 0,
    minHeight: 0,
    boxShadow: '0 0.7rem 1.8rem rgba(0, 0, 0, 0.34)',
  },
  homeAboutWindow: {
    minHeight: '660px',
  },
  homeBtopWindow: {
    minHeight: '760px',
  },
  homeVideoWindow: {
    aspectRatio: '16 / 10',
  },
  hidden: {
    display: 'none',
  },
  windowContent: {
    position: 'relative',
    minHeight: 0,
    flexGrow: 1,
    overflow: 'auto',
  },
  terminal: {
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: '1rem',
    color: tokens.ink,
    backgroundColor: '#0a0a0d',
    fontSize: {
      default: '0.75rem',
      '@media (max-width: 720px)': '0.75rem',
    },
    lineHeight: 1.7,
  },
  terminalOutput: {
    minHeight: 0,
    flexGrow: 1,
    overflow: 'auto',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  terminalLine: {
    margin: 0,
  },
  terminalForm: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.55rem',
    marginTop: '0.5rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
    paddingTop: '0.65rem',
  },
  prompt: {
    color: tokens.green,
    fontWeight: 700,
  },
  terminalInput: {
    minWidth: 0,
    minHeight: '44px',
    flexGrow: 1,
    paddingInline: '0.65rem',
    color: tokens.ink,
    caretColor: tokens.green,
    backgroundColor: 'rgba(240, 238, 245, 0.04)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    borderRadius: 0,
    font: 'inherit',
    fontSize: '16px',
  },
  files: {
    display: 'grid',
    alignContent: 'start',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 420px)': '1fr',
    },
    gap: '0.65rem',
    padding: '1rem',
  },
  fileLink: {
    minHeight: '48px',
    display: 'flex',
    alignItems: 'center',
    paddingInline: '0.85rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'rgba(240, 238, 245, 0.04)',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    fontSize: '0.75rem',
    textDecorationLine: 'none',
  },
  videoWindow: {
    width: '100%',
    height: '100%',
    minHeight: 0,
    padding: '0.45rem',
    backgroundColor: '#0a0a0d',
  },
  videoFrame: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
    height: '100%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    backgroundColor: tokens.panel,
  },
  videoFill: {
    width: '100%',
    height: '100%',
    borderWidth: 0,
  },
  videoFacade: {
    position: 'relative',
    display: 'block',
    padding: 0,
    color: tokens.ink,
    backgroundColor: tokens.panel,
    cursor: 'pointer',
  },
  videoImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  videoShade: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(180deg, transparent 52%, rgba(0, 0, 0, 0.44))',
    pointerEvents: 'none',
  },
  play: {
    position: 'absolute',
    zIndex: 1,
    top: '50%',
    left: '50%',
    width: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    height: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    display: 'grid',
    placeItems: 'center',
    backgroundColor: tokens.green,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.black,
    transform: 'translate(-50%, -50%)',
  },
  playIcon: {
    width: '16px',
    height: '18px',
    marginLeft: '4px',
    backgroundColor: tokens.black,
    clipPath: 'polygon(0 0, 100% 50%, 0 100%)',
  },
  launcher: {
    position: 'absolute',
    zIndex: 100,
    left: '50%',
    top: '50%',
    bottom: {
      default: 'auto',
      '@media (max-width: 720px)': 'auto',
    },
    width: {
      default: 'min(430px, calc(100% - 32px))',
      '@media (max-width: 720px)': 'calc(100% - 16px)',
    },
    maxHeight: 'calc(100% - 64px)',
    overflowY: 'auto',
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#11121a',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.green,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.52)',
    transform: {
      default: 'translate(-50%, -50%)',
      '@media (max-width: 720px)': 'translate(-50%, -50%)',
    },
  },
  launcherButton: {
    minHeight: '52px',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    paddingInline: '0.85rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'rgba(240, 238, 245, 0.04)',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    font: 'inherit',
    fontSize: '0.75rem',
    textAlign: 'left',
    cursor: 'pointer',
  },
  launcherIcon: {
    width: '22px',
    height: '22px',
    flexShrink: 0,
    display: 'block',
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
});
