import * as stylex from '@stylexjs/stylex';
import { tokens } from './landing.stylex';

export const desktopStyles = stylex.create({
  desktop: {
    position: 'relative',
    overflow: 'hidden',
    width: '100%',
    height: {
      default: 'clamp(640px, 78svh, 840px)',
      '@media (max-width: 720px)': 'min(720px, calc(100svh - 34px))',
    },
    minHeight: {
      default: '640px',
      '@media (max-width: 720px)': '620px',
    },
    isolation: 'isolate',
    color: tokens.ink,
    backgroundColor: '#11121a',
    backgroundImage: "url('/images/silk.webp')",
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
  },
  canvas: {
    position: 'absolute',
    zIndex: 0,
    inset: 0,
    width: '100%',
    height: '100%',
    display: 'block',
    opacity: 0,
    pointerEvents: 'none',
    transitionProperty: 'opacity',
    transitionDuration: {
      default: '180ms',
      '@media (prefers-reduced-motion: reduce)': '0ms',
    },
    transitionTimingFunction: 'ease-out',
  },
  canvasReady: {
    opacity: 1,
  },
  shade: {
    position: 'absolute',
    zIndex: 1,
    inset: 0,
    pointerEvents: 'none',
    backgroundImage: 'linear-gradient(180deg, rgba(4, 5, 8, 0.18), rgba(4, 5, 8, 0.36))',
  },
  topbar: {
    position: 'absolute',
    zIndex: 80,
    top: 0,
    left: 0,
    right: 0,
    height: '46px',
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr auto 1fr',
      '@media (max-width: 540px)': '1fr auto',
    },
    alignItems: 'center',
    paddingInline: {
      default: '0.75rem',
      '@media (max-width: 540px)': '0.5rem',
    },
    color: tokens.ink,
    backgroundColor: 'rgba(8, 9, 13, 0.9)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.lineStrong,
    fontSize: '0.75rem',
  },
  brand: {
    display: {
      default: 'inline',
      '@media (max-width: 540px)': 'none',
    },
    justifySelf: 'start',
    fontWeight: 700,
    letterSpacing: '0.06em',
  },
  workspaces: {
    display: 'flex',
    justifyContent: 'center',
    justifySelf: {
      default: 'center',
      '@media (max-width: 540px)': 'start',
    },
    gap: '0.3rem',
  },
  workspace: {
    width: '44px',
    height: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    color: tokens.muted,
    backgroundColor: 'transparent',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'transparent',
    font: 'inherit',
    cursor: 'pointer',
  },
  workspaceActive: {
    color: tokens.black,
    backgroundColor: tokens.green,
    borderColor: tokens.green,
  },
  clock: {
    justifySelf: 'end',
    color: tokens.ink,
    fontVariantNumeric: 'tabular-nums',
    whiteSpace: 'nowrap',
  },
  windowsLayer: {
    position: 'absolute',
    zIndex: 10,
    inset: {
      default: '46px 0 64px',
      '@media (max-width: 720px)': '46px 0 118px',
    },
  },
  emptyWorkspace: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    padding: '2rem',
    color: tokens.ink,
    fontSize: {
      default: '0.8rem',
      '@media (max-width: 720px)': '0.75rem',
    },
    textAlign: 'center',
  },
  window: {
    position: 'absolute',
    minWidth: '280px',
    minHeight: '210px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    color: tokens.ink,
    backgroundColor: 'rgba(12, 13, 19, 0.96)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.42)',
  },
  windowFocused: {
    borderColor: tokens.green,
    boxShadow: '0 1.75rem 4.5rem rgba(0, 0, 0, 0.5)',
  },
  windowMaximized: {
    inset: '8px',
    width: 'auto',
    height: 'auto',
  },
  windowMobile: {
    inset: '8px',
    width: 'auto',
    height: 'auto',
    minWidth: 0,
    minHeight: 0,
  },
  hidden: {
    display: 'none',
  },
  titlebar: {
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    gap: '0.65rem',
    paddingLeft: '0.75rem',
    color: tokens.muted,
    backgroundColor: 'rgba(22, 24, 32, 0.98)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.line,
    userSelect: 'none',
    cursor: {
      default: 'move',
      '@media (max-width: 720px)': 'default',
    },
    touchAction: 'none',
  },
  title: {
    minWidth: 0,
    flexGrow: 1,
    overflow: 'hidden',
    fontSize: '0.75rem',
    fontWeight: 600,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  windowControls: {
    alignSelf: 'stretch',
    display: 'flex',
  },
  windowControl: {
    width: '44px',
    minHeight: '44px',
    display: 'grid',
    placeItems: 'center',
    padding: 0,
    color: {
      default: tokens.muted,
      ':hover': tokens.ink,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': 'rgba(240, 238, 245, 0.08)',
      ':active': tokens.green,
    },
    borderWidth: 0,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.line,
    font: 'inherit',
    cursor: 'pointer',
  },
  windowContent: {
    position: 'relative',
    minHeight: 0,
    flexGrow: 1,
    overflow: 'auto',
  },
  aboutContent: {
    minHeight: '100%',
    display: 'flex',
    alignItems: 'flex-end',
    padding: {
      default: 'clamp(1.5rem, 4vw, 3.5rem)',
      '@media (max-width: 720px)': '1.5rem',
    },
    backgroundImage: 'linear-gradient(135deg, rgba(122, 162, 247, 0.08), transparent 48%)',
  },
  heroTitle: {
    minWidth: 0,
    maxWidth: '11ch',
    margin: 0,
    color: tokens.ink,
    fontSize: {
      default: 'clamp(2.7rem, 5.5vw, 6.2rem)',
      '@media (max-width: 720px)': 'clamp(2.3rem, 12vw, 4rem)',
    },
    fontWeight: 500,
    letterSpacing: '-0.075em',
    lineHeight: 0.94,
    overflowWrap: 'anywhere',
  },
  heroLink: {
    color: tokens.blue,
    textDecorationThickness: '0.08em',
    textUnderlineOffset: '0.12em',
  },
  terminal: {
    height: '100%',
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: '1rem',
    color: tokens.ink,
    backgroundColor: '#0a0a0d',
    fontSize: {
      default: '0.75rem',
      '@media (max-width: 720px)': '0.75rem',
    },
    lineHeight: 1.7,
  },
  terminalOutput: {
    minHeight: 0,
    flexGrow: 1,
    overflow: 'auto',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
  },
  terminalLine: {
    margin: 0,
  },
  terminalForm: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.55rem',
    marginTop: '0.5rem',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.line,
    paddingTop: '0.65rem',
  },
  prompt: {
    color: tokens.green,
    fontWeight: 700,
  },
  terminalInput: {
    minWidth: 0,
    minHeight: '44px',
    flexGrow: 1,
    paddingInline: '0.65rem',
    color: tokens.ink,
    caretColor: tokens.green,
    backgroundColor: 'rgba(240, 238, 245, 0.04)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    borderRadius: 0,
    font: 'inherit',
    fontSize: '16px',
  },
  files: {
    display: 'grid',
    alignContent: 'start',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 420px)': '1fr',
    },
    gap: '0.65rem',
    padding: '1rem',
  },
  fileLink: {
    minHeight: '48px',
    display: 'flex',
    alignItems: 'center',
    paddingInline: '0.85rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'rgba(240, 238, 245, 0.04)',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    fontSize: '0.75rem',
    textDecorationLine: 'none',
  },
  videos: {
    minHeight: '100%',
    display: 'grid',
    alignContent: 'start',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 720px)': '1fr',
    },
    gap: '1rem',
    padding: {
      default: '1rem',
      '@media (max-width: 720px)': '0.75rem',
    },
    backgroundColor: '#0a0a0d',
  },
  videoFrame: {
    position: 'relative',
    overflow: 'hidden',
    aspectRatio: '16 / 9',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    backgroundColor: tokens.panel,
  },
  videoFill: {
    width: '100%',
    height: '100%',
    borderWidth: 0,
  },
  videoFacade: {
    position: 'relative',
    display: 'block',
    padding: 0,
    color: tokens.ink,
    backgroundColor: tokens.panel,
    cursor: 'pointer',
  },
  videoImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  videoShade: {
    position: 'absolute',
    inset: 0,
    backgroundImage: 'linear-gradient(180deg, transparent 52%, rgba(0, 0, 0, 0.44))',
    pointerEvents: 'none',
  },
  play: {
    position: 'absolute',
    zIndex: 1,
    top: '50%',
    left: '50%',
    width: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    height: {
      default: '64px',
      '@media (max-width: 720px)': '56px',
    },
    display: 'grid',
    placeItems: 'center',
    backgroundColor: tokens.green,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.black,
    transform: 'translate(-50%, -50%)',
  },
  playIcon: {
    width: '16px',
    height: '18px',
    marginLeft: '4px',
    backgroundColor: tokens.black,
    clipPath: 'polygon(0 0, 100% 50%, 0 100%)',
  },
  resizeHandle: {
    position: 'absolute',
    zIndex: 2,
    right: 0,
    bottom: 0,
    width: '44px',
    height: '44px',
    padding: 0,
    color: 'transparent',
    backgroundColor: 'transparent',
    backgroundImage: 'linear-gradient(135deg, transparent 48%, rgba(240, 238, 245, 0.52) 49%, rgba(240, 238, 245, 0.52) 54%, transparent 55%)',
    borderWidth: 0,
    cursor: 'nwse-resize',
    touchAction: 'none',
  },
  dock: {
    position: 'absolute',
    zIndex: 90,
    left: '50%',
    bottom: {
      default: '10px',
      '@media (max-width: 720px)': 'max(8px, env(safe-area-inset-bottom))',
    },
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '0.5rem',
    width: {
      default: 'auto',
      '@media (max-width: 720px)': 'calc(100% - 16px)',
    },
    maxWidth: 'calc(100% - 16px)',
    padding: '0.4rem',
    backgroundColor: 'rgba(8, 9, 13, 0.94)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.lineStrong,
    transform: 'translateX(-50%)',
  },
  dockButton: {
    minWidth: {
      default: '88px',
      '@media (max-width: 540px)': 'auto',
    },
    minHeight: '46px',
    display: 'grid',
    placeItems: 'center',
    paddingInline: {
      default: '0.8rem',
      '@media (max-width: 540px)': '0.45rem',
    },
    color: {
      default: tokens.muted,
      ':hover': tokens.ink,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': 'rgba(240, 238, 245, 0.08)',
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: 'transparent',
      ':hover': tokens.lineStrong,
      ':active': tokens.green,
    },
    font: 'inherit',
    fontSize: {
      default: '0.75rem',
      '@media (max-width: 540px)': '0.75rem',
    },
    cursor: 'pointer',
    textDecorationLine: 'none',
  },
  dockButtonActive: {
    color: tokens.black,
    backgroundColor: tokens.green,
    borderColor: tokens.green,
  },
  launcher: {
    position: 'absolute',
    zIndex: 100,
    left: {
      default: '50%',
      '@media (max-width: 720px)': '8px',
    },
    bottom: {
      default: '70px',
      '@media (max-width: 720px)': '126px',
    },
    width: {
      default: 'min(430px, calc(100% - 32px))',
      '@media (max-width: 720px)': 'calc(100% - 16px)',
    },
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#11121a',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: tokens.green,
    boxShadow: '0 1.5rem 4rem rgba(0, 0, 0, 0.52)',
    transform: {
      default: 'translateX(-50%)',
      '@media (max-width: 720px)': 'none',
    },
  },
  launcherButton: {
    minHeight: '52px',
    paddingInline: '0.85rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
      ':active': tokens.black,
    },
    backgroundColor: {
      default: 'rgba(240, 238, 245, 0.04)',
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: tokens.line,
      ':hover': tokens.green,
      ':active': tokens.green,
    },
    font: 'inherit',
    fontSize: '0.75rem',
    textAlign: 'left',
    cursor: 'pointer',
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
});
