import * as stylex from '@stylexjs/stylex';
import { tokens } from './landing.stylex';

export const menuStyles = stylex.create({
  focusRing: {
    outline: {
      default: 'none',
      ':focus-visible': `2px solid ${tokens.green}`,
    },
    outlineOffset: {
      default: 0,
      ':focus-visible': '3px',
    },
  },
  controls: {
    position: 'fixed',
    zIndex: 103,
    top: {
      default: '16px',
      '@media (max-width: 720px)': '12px',
    },
    left: {
      default: '16px',
      '@media (max-width: 720px)': '12px',
    },
    right: {
      default: '16px',
      '@media (max-width: 720px)': '12px',
    },
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    opacity: 1,
    transform: 'translateY(0)',
    pointerEvents: 'none',
    transitionProperty: 'opacity, transform',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
  },
  controlsHidden: {
    opacity: 0,
    transform: 'translateY(-72px)',
    pointerEvents: 'none',
  },
  toggle: {
    minWidth: {
      default: '108px',
      '@media (max-width: 420px)': '96px',
    },
    minHeight: '48px',
    paddingBlock: '0.7rem',
    paddingInline: '0.85rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.65rem',
    color: {
      default: tokens.ink,
      ':hover': '#0a0a0d',
    },
    backgroundColor: {
      default: '#111015',
      ':hover': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: 'rgba(242, 236, 227, 0.72)',
      ':hover': tokens.green,
    },
    borderRadius: 0,
    fontSize: '0.74rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
    cursor: 'pointer',
    pointerEvents: 'auto',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
  },
  toggleOpen: {
    color: {
      default: '#ff75ad',
      ':hover': tokens.black,
    },
    borderColor: 'rgba(255, 117, 173, 0.74)',
  },
  rightActions: {
    display: 'flex',
    alignItems: 'stretch',
    pointerEvents: 'none',
  },
  searchAction: {
    width: '48px',
    minWidth: '48px',
    minHeight: '48px',
    padding: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
    },
    backgroundColor: {
      default: '#111015',
      ':hover': tokens.green,
    },
    borderWidth: '1px',
    borderRightWidth: 0,
    borderStyle: 'solid',
    borderColor: {
      default: 'rgba(242, 236, 227, 0.72)',
      ':hover': tokens.green,
    },
    borderRadius: 0,
    cursor: 'pointer',
    pointerEvents: 'auto',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
  },
  download: {
    minHeight: '48px',
    paddingBlock: '0.7rem',
    paddingInline: {
      default: '0.95rem',
      '@media (max-width: 420px)': '0.75rem',
    },
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.55rem',
    color: {
      default: tokens.ink,
      ':hover': tokens.black,
    },
    backgroundColor: {
      default: '#111015',
      ':hover': tokens.green,
    },
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: {
      default: 'rgba(242, 236, 227, 0.72)',
      ':hover': tokens.green,
    },
    borderRadius: 0,
    fontSize: '0.74rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textDecorationLine: 'none',
    pointerEvents: 'auto',
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '140ms',
    transitionTimingFunction: 'ease',
  },
  toggleIcon: {
    width: '18px',
    height: '18px',
    display: 'block',
    flexShrink: 0,
    overflow: 'visible',
  },
  scrim: {
    position: 'fixed',
    zIndex: 100,
    inset: 0,
    width: '100%',
    height: '100%',
    padding: 0,
    backgroundColor: 'rgba(4, 4, 8, 0.72)',
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0,
    visibility: 'hidden',
    pointerEvents: 'none',
    cursor: 'default',
    transitionProperty: 'opacity, visibility',
    transitionDuration: '160ms',
    transitionTimingFunction: 'ease',
  },
  scrimOpen: {
    opacity: 1,
    visibility: 'visible',
    pointerEvents: 'auto',
  },
  panel: {
    position: 'fixed',
    zIndex: 102,
    top: {
      default: '50%',
      '@media (max-width: 620px)': '68px',
    },
    left: '50%',
    width: {
      default: 'min(390px, calc(100vw - 32px))',
      '@media (max-width: 720px)': 'calc(100vw - 24px)',
    },
    maxWidth: '390px',
    maxHeight: {
      default: 'calc(100dvh - 92px)',
      '@media (max-width: 620px)': 'calc(100dvh - 80px)',
    },
    padding: {
      default: '1.35rem 1.45rem 1.45rem',
      '@media (max-width: 420px)': '1.15rem 1rem 1rem',
    },
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    scrollbarColor: '#635760 #110f15',
    color: '#f2ece3',
    backgroundColor: '#110f15',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: '#e8e0d7',
    boxShadow: '0 22px 64px rgba(0, 0, 0, 0.5)',
    opacity: 0,
    visibility: 'hidden',
    pointerEvents: 'none',
    transform: {
      default: 'translate(-50%, calc(-50% - 14px)) scale(0.985)',
      '@media (max-width: 620px)': 'translate(-50%, -14px) scale(0.985)',
    },
    transitionProperty: 'opacity, visibility, transform',
    transitionDuration: '160ms',
    transitionTimingFunction: 'ease',
  },
  panelOpen: {
    opacity: 1,
    visibility: 'visible',
    pointerEvents: 'auto',
    transform: {
      default: 'translate(-50%, -50%) scale(1)',
      '@media (max-width: 620px)': 'translate(-50%, 0) scale(1)',
    },
  },
  panelGraph: {
    width: {
      default: 'min(1000px, calc(100vw - 32px))',
      '@media (max-width: 720px)': 'calc(100vw - 24px)',
    },
    maxWidth: '1000px',
    padding: {
      default: '1rem',
      '@media (max-width: 420px)': '0.8rem',
    },
  },
  searchWorkspace: {
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(240px, 280px) minmax(0, 1fr)',
      '@media (max-width: 820px)': 'minmax(0, 1fr)',
    },
    alignItems: 'start',
    gap: '0.75rem',
  },
  searchResultsPane: {
    minWidth: 0,
    overflow: 'hidden',
    backgroundColor: '#0b0a0e',
    borderWidth: 0,
  },
  searchResultsHeader: {
    minHeight: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    paddingInline: '0.7rem',
    color: '#948d88',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(242, 236, 227, 0.2)',
    fontSize: '0.7rem',
    letterSpacing: '0.07em',
    textTransform: 'uppercase',
  },
  searchResultsList: {
    margin: 0,
    padding: '0.35rem',
    display: 'grid',
    gap: '0.25rem',
    listStyle: 'none',
    '@media (max-width: 820px)': {
      gridAutoColumns: 'min(250px, 78vw)',
      gridAutoFlow: 'column',
      gridTemplateRows: '1fr',
      overflowX: 'auto',
      overscrollBehaviorX: 'contain',
    },
  },
  searchResultItem: {
    minWidth: 0,
    margin: 0,
    padding: 0,
  },
  searchResult: {
    width: '100%',
    minHeight: '49px',
    display: 'grid',
    gridTemplateColumns: '22px minmax(0, 1fr) 10px',
    alignItems: 'center',
    gap: '0.85rem',
    paddingBlock: '0.65rem',
    paddingInline: '0.85rem',
    color: {
      default: '#f2ece3',
      ':hover': '#ff75ad',
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': '#282229',
    },
    borderWidth: 0,
    borderRadius: 0,
    font: 'inherit',
    fontSize: '0.9rem',
    letterSpacing: '0.01em',
    textAlign: 'left',
    cursor: 'pointer',
    transitionProperty: 'color, background-color',
    transitionDuration: '100ms',
    transitionTimingFunction: 'linear',
  },
  searchResultActive: {
    color: '#ff75ad',
    backgroundColor: '#282229',
  },
  searchResultCopy: {
    minWidth: 0,
    display: 'grid',
    gap: '0.2rem',
  },
  searchResultTitle: {
    minWidth: 0,
    overflowWrap: 'anywhere',
    fontSize: '1rem',
    fontWeight: 500,
    lineHeight: 1.35,
  },
  searchResultDetail: {
    minWidth: 0,
    overflow: 'hidden',
    color: 'currentColor',
    fontSize: '0.72rem',
    lineHeight: 1.4,
    letterSpacing: '0.01em',
    opacity: 0.58,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  searchResultsState: {
    minHeight: '90px',
    margin: 0,
    padding: '0.8rem',
    color: '#948d88',
    fontSize: '0.8rem',
    lineHeight: 1.5,
  },
  prompt: {
    margin: '0 0 0.45rem',
    display: 'block',
    color: '#948d88',
    fontSize: '0.78rem',
    letterSpacing: '0.02em',
  },
  searchField: {
    position: 'relative',
    width: '100%',
    marginBottom: '0.85rem',
  },
  search: {
    width: '100%',
    minHeight: '48px',
    paddingBlock: '0.7rem',
    paddingLeft: '0.85rem',
    paddingRight: '5.25rem',
    color: {
      default: '#f2ece3',
      '::placeholder': '#948d88',
    },
    backgroundColor: '#0b0a0e',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(242, 236, 227, 0.38)',
    borderRadius: 0,
    caretColor: '#ff75ad',
    fontSize: '1rem',
    lineHeight: 1.4,
  },
  searchShortcut: {
    position: 'absolute',
    top: '50%',
    right: '0.75rem',
    paddingBlock: '0.12rem',
    paddingInline: '0.34rem',
    color: '#948d88',
    backgroundColor: '#110f15',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(242, 236, 227, 0.28)',
    borderRadius: 0,
    fontFamily: 'inherit',
    fontSize: '0.62rem',
    lineHeight: 1.4,
    letterSpacing: '0.02em',
    pointerEvents: 'none',
    opacity: 1,
    transform: 'translateY(-50%)',
    transitionProperty: 'opacity',
    transitionDuration: '100ms',
    transitionTimingFunction: 'linear',
  },
  searchShortcutHidden: {
    opacity: 0,
  },
  list: {
    margin: 0,
    padding: 0,
    display: 'grid',
    gap: '0.2rem',
    listStyle: 'none',
  },
  listItem: {
    margin: 0,
    padding: 0,
  },
  empty: {
    minHeight: '72px',
    paddingBlock: '1rem',
    paddingInline: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    color: '#948d88',
    fontSize: '0.78rem',
    lineHeight: 1.6,
  },
  menuLink: {
    minHeight: '49px',
    paddingBlock: '0.65rem',
    paddingInline: '0.85rem',
    display: 'grid',
    gridTemplateColumns: '22px minmax(0, 1fr) 10px',
    alignItems: 'center',
    gap: '0.85rem',
    color: {
      default: '#f2ece3',
      ':hover': '#ff75ad',
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': '#282229',
    },
    fontSize: '0.9rem',
    letterSpacing: '0.01em',
    textDecorationLine: 'none',
    transitionProperty: 'color, background-color',
    transitionDuration: '100ms',
    transitionTimingFunction: 'linear',
  },
  menuLinkActive: {
    color: '#ff75ad',
    backgroundColor: '#282229',
  },
  icon: {
    width: '20px',
    height: '20px',
    display: 'block',
    overflow: 'visible',
  },
  linkCopy: {
    minWidth: 0,
    display: 'grid',
    gap: '0.14rem',
  },
  linkLabel: {
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  linkDetail: {
    minWidth: 0,
    overflow: 'hidden',
    color: 'currentColor',
    fontSize: '0.64rem',
    lineHeight: 1.35,
    letterSpacing: '0.01em',
    opacity: 0.52,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chevron: {
    width: '7px',
    height: '7px',
    justifySelf: 'end',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'currentColor',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'currentColor',
    opacity: 0.52,
    transform: 'rotate(45deg)',
  },
});
